baseURL = "https://altinn.github.io/docs/"
languageCode = "nb"
defaultContentLanguage = "nb"

contentDir = "content"
staticDir = "static"
publishDir = "public"

title = "Altinn docs"
theme = "hugo-theme-docdock"
metadataFormat = "yaml"
pluralizeListTitles = false
preservetaxonomynames = true
enableEmoji = true
enableGitInfo = false
disableKinds = ["RSS"] # page home section taxonomy taxonomyTerm RSS sitemap robotsTXT 404

[blackfriday]
fractions = false # disable automatic fraction rendering

[params]
editURL = "https://github.com/altinn/docs/blob/master/content/"
noHomeIcon = true # default is false
noSearch = false # default is false
disableNavChevron = true
showVisitedLinks = false # default is false
#themeVariant = "blue" # choose theme variant "green", "gold", "gray", blue" (default)


[outputs]
home = ["HTML", "JSON"] # JSON generates index.json file used by search


[[menu.shortcuts]]
pre = "<h3>Lenker</h3>"
name = "<i class='fa fa-fw fa-star'></i> Designsystem"
identifier = "designsystem"
url = "https://altinn.github.io/DesignSystem"
weight = 20

[[menu.shortcuts]]
name = "<i class='fa fa-fw fa-info-circle'></i> Altinnett"
identifier = "altinnett"
url = "https://altinnett.brreg.no/"
weight = 30

[[menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> Kred"
url = "/credits"
weight = 40

[[menu.shortcuts]]
name = "<i class='fa fa-fw fa-github'></i> GitHub"
identifier = "docs-repo"
url = "https://github.com/altinn/docs"
weight = 50
