baseURL = "https://altinn.github.io/docs/"
languageCode = "nb"
defaultContentLanguage = "nb"

contentDir = "content"
staticDir = "static"
publishDir = "public"

title = "Altinn docs"
theme = "hugo-theme-docdock"
metadataFormat = "yaml"
pluralizeListTitles = false
preservetaxonomynames = true
enableEmoji = true
enableGitInfo = false
disableKinds = ["RSS"] # page home section taxonomy taxonomyTerm RSS sitemap robotsTXT 404

[blackfriday]
fractions = false # disable automatic fraction rendering

[params]
editURL = "https://github.com/altinn/docs/blob/master/content/"
noHomeIcon = true # default is false
noSearch = false # default is false
showVisitedLinks = false # default is false
#themeVariant = "blue" # choose theme variant "green", "gold", "gray", blue" (default)


[outputs]
home = ["HTML", "JSON"] # JSON generates index.json file used by search
